services:
  - type: web
    name: Blue-sky
    env: static
    plan: free  # 無料プラン
    region: oregon  # デプロイ先リージョンをオレゴンに設定
    routes:
      - type: rewrite
        source: "/arc-sw.js"
        destination: "https://arc.io/arc-sw.js"
