services:
  - type: web
    name: Blue-sky
    env: static
    plan: free  # 無料プラン
    region: oregon  # デプロイ先リージョンをオレゴンに設定
    routes:
      - src: "/arc-sw.js"
        dest: "https://arc.io/arc-sw.js"
